parameters:
    chaplean_gitlab_client.api.token: '%chaplean_gitlab_client.token%'
    chaplean_gitlab_client.api.url: '%chaplean_gitlab_client.url%'

services:
    gitlab_api:
        class: Chaplean\Bundle\GitlabClientBundle\Api\GitlabApi
        arguments:
            - '@guzzle.client.gitlab_api'
            - '@event_dispatcher'
            - '%chaplean_gitlab_client.api.url%'
            - '%chaplean_gitlab_client.api.token%'
